:children_crossing: Add new config api v2alpha1
Bankdata/styra-controller pull request #17
Opened 2023-03-31 10:12 UTC by blacksails

The old API is messy and not well documented. This adds a new config API
while keeping backwards compatatibility with the old API.

2023-03-31 10:19 UTC, blacksails commented on api/config/v2alpha1/projectconfig_types.go
> +	// TODO: how does the level work after the introduction of the new logging
Write a proper description.

2023-03-31 10:19 UTC, blacksails commented on config/samples/config_v2alpha1_projectconfig.yaml
> +  # TODO(user): Add fields here
Add full example

2023-03-31 10:19 UTC, blacksails commented on internal/config/config.go
> +// Package config provides utilities for reading configfiles
Add license notice

2023-03-31 11:21 UTC, bdjgs commented on api/config/v1/projectconfig_types.go
> +// ToV2Alpha1 returns this ProjectConfig converted to a v2alpha2.ProjectConfig
```suggestion
// ToV2Alpha1 returns this ProjectConfig converted to a v2alpha1.ProjectConfig
```

2023-04-05 08:56 UTC, simlau requested changes

2023-04-05 08:56 UTC, simlau commented on api/config/v2alpha1/projectconfig_types_test.go
> +					RepoPrefix: "https://git.bankdata.eficode.io/",
Change to some repo that is not bankdatas

2023-04-05 09:02 UTC, simlau requested changes

2023-04-05 09:02 UTC, simlau commented on api/config/v2alpha1/projectconfig_types_test.go
> +		),
```suggestion
			[]*v2alpha1.GitCredential{
				{
					User:       "",
					Password:   "",
					RepoPrefix: "https://somegitrepo.com/",
				},
			},
			"https://somegitrepo.com/test/test.git",
			&v2alpha1.GitCredential{
				User:       "",
				Password:   "",
				RepoPrefix: "https://somegitrepo.com/",
			},
		),
		Entry("get eficode credentials should return longest match",
			[]*v2alpha1.GitCredential{
				{
					User:       "",
					Password:   "",
					RepoPrefix: "https://somegitrepo.com/",
				},
				{
					User:       "",
					Password:   "",
					RepoPrefix: "https://somegitrepo.com/test",
				},
			},
			"https://somegitrepo.com/test/test.git",
			&v2alpha1.GitCredential{
				User:       "",
				Password:   "",
				RepoPrefix: "https://somegitrepo.com/test",
			},
		),
```

2023-04-05 09:13 UTC, simlau approved these changes

2023-04-05 09:13 UTC, merged